[log]
level = "INFO"

[providers]
[providers.file]
filename = "traefik-dynamic.toml"
watch = true

[api]
debug = false
dashboard = false
insecure = true

[entryPoints]
[entryPoints.http]
address = ":80"
[entryPoints.http.http.redirections]
[entryPoints.http.http.redirections.entryPoint]
to = "https"

[entryPoints.https]
address = ":443"
